-- creazione tabelle
CREATE TABLE UTENTI(
USERNAME VARCHAR2(50) PRIMARY KEY,
PASSWORD VARCHAR2(25) NOT NULL,
NOME VARCHAR2(30) NOT NULL,
COGNOME VARCHAR2(30) NOT NULL,
SESSO CHAR(1) NOT NULL,
DATA_NASCITA DATE NOT NULL,
EMAIL VARCHAR2(70) NOT NULL UNIQUE,
FOTO BLOB,
CELLULARE NUMBER(11) NOT NULL,
VIA VARCHAR2(35) NOT NULL,
CITTA VARCHAR2(20) NOT NULL,
CAP NUMBER(5) NOT NULL,
NOMEFILE VARCHAR2(50)
)TABLESPACE cpooling_dati LOB(FOTO) STORE AS LOB_FOTO(TABLESPACE foto_utenti)
STORAGE(INITIAL 2800 K);

CREATE TABLE PASSEGGERI( 
USERN VARCHAR2(50) PRIMARY KEY, 
NUM_DOC VARCHAR2(10) NOT NULL, 
SCAD_DOC DATE NOT NULL 
) TABLESPACE cpooling_dati STORAGE (INITIAL 536K); 

CREATE TABLE AUTISTI( 
USERN VARCHAR2(50) PRIMARY KEY, 
NUM_PAT VARCHAR2(10) NOT NULL, 
SCAD_PAT DATE    NOT NULL, 
MARCA_AUTO VARCHAR2(20) NOT NULL, 
MODELLO_AUTO VARCHAR2(20) NOT NULL, 
COLORE_AUTO VARCHAR2(20) 
) TABLESPACE cpooling_dati STORAGE (INITIAL 254K); 

CREATE TABLE PRENOTAZIONI( 
CODICE NUMBER(6) PRIMARY KEY, 
STATO CHAR(9), 
PASSEGGERO VARCHAR2(50), 
VIAGGIO NUMBER(5) NOT NULL 
) TABLESPACE cpooling_dati STORAGE (INITIAL 3000K); 

CREATE TABLE VIAGGI( 
CODV NUMBER(5) PRIMARY KEY, 
STATO VARCHAR2(6) NOT NULL, 
DATA_P DATE NOT NULL, 
ORA_P VARCHAR2(5) NOT NULL, 
DURATA INTEGER NOT NULL, 
NUM_POSTI_DISPONIBILI NUMBER(1), 
NUM_ATTESA NUMBER(2), 
CONTRIBUTO NUMBER(3,1), 
DESCRIZIONE_BAGAGLI VARCHAR2(250), 
NUMERO_BAGAGLI NUMBER(1) NOT NULL, 
ANIMALI CHAR(2) NOT NULL, 
LUOGO_ARRIVO NUMBER(7) NOT NULL, 
LUOGO_PARTENZA NUMBER(7) NOT NULL, 
AUTISTA VARCHAR2(50) NOT NULL 
) TABLESPACE cpooling_dati STORAGE (INITIAL 2800 K);

ALTER TABLE VIAGGI MODIFY CONTRIBUTO number(3,1);

CREATE TABLE GIUDIZI(
CODICE NUMBER(6) PRIMARY KEY,
STELLE NUMBER(1) NOT NULL,
COMMENTO CLOB NOT NULL,
GIUDICANTE VARCHAR2(50),
GIUDICATO VARCHAR2(50)
)TABLESPACE cpooling_dati
LOB (COMMENTO) STORE AS LOB_COMMENTO(TABLESPACE commenti_utenti)
STORAGE (INITIAL 79100 K);

CREATE TABLE SOSTE( 
ID_LUOGO NUMBER(7), 
ID_VIAGGIO NUMBER(5),
CONSTRAINT PK_SOSTE PRIMARY KEY(ID_LUOGO,ID_VIAGGIO) 
) TABLESPACE cpooling_dati STORAGE (INITIAL 12000K);

CREATE TABLE LUOGHI( 
LATITUDINE NUMBER(9,6), 
LONGITUDINE NUMBER(9,6), 
CAP_CITTA NUMBER(5), 
ID_LUOGO NUMBER(7) PRIMARY KEY, 
UNIQUE(LONGITUDINE,LATITUDINE) 
) TABLESPACE cpooling_dati STORAGE (INITIAL 65600K);

ALTER TABLE luoghi MODIFY latitudine number(9,6);
ALTER TABLE luoghi MODIFY longitudine number(9,6);

CREATE TABLE CITTA( 
CAP NUMBER(5) PRIMARY KEY, 
NOME VARCHAR2(20) NOT NULL, 
PROVINCIA NUMBER(5) NOT NULL 
) TABLESPACE cpooling_dati STORAGE (INITIAL 340K);

CREATE TABLE STORICO_PRENOTAZIONI( 
CODICE NUMBER(6) PRIMARY KEY, 
STATO CHAR(9), 
PASSEGGERO VARCHAR2(50), 
VIAGGIO NUMBER(5) NOT NULL 
) TABLESPACE storico STORAGE (INITIAL 30500K);

CREATE TABLE STORICO_VIAGGI( 
CODV NUMBER(5) PRIMARY KEY, 
STATO VARCHAR2(6) NOT NULL, 
DATA_P DATE NOT NULL, 
ORA_P NUMBER(5) NOT NULL, 
DURATA INTEGER NOT NULL, 
NUM_POSTI_DISPONIBILI NUMBER(1), 
NUM_ATTESA NUMBER(2), 
CONTRIBUTO NUMBER(3,2), 
DESCRIZIONE_BAGAGLI VARCHAR2(250), 
NUMERO_BAGAGLI NUMBER(1) NOT NULL, 
ANIMALI CHAR(2) NOT NULL, 
LUOGO_ARRIVO NUMBER(7) NOT NULL, 
LUOGO_PARTENZA NUMBER(7) NOT NULL, 
AUTISTA VARCHAR2(50) NOT NULL
) TABLESPACE storico STORAGE (INITIAL 34500 K);

--DEFINIZIONE VINCOLI (ancora non inseriti)


ALTER TABLE PASSEGGERI ADD CONSTRAINT FK_UTENTI_PASSEGGERI
FOREIGN KEY (Usern) REFERENCES UTENTI (Username); 

ALTER TABLE AUTISTI ADD CONSTRAINT FK_UTENTI_AUTISTI 
FOREIGN KEY (Usern) REFERENCES UTENTI(Username); 

ALTER TABLE PRENOTAZIONI ADD CONSTRAINT FK_PRENOTAZIONI_PASSEGGERO
FOREIGN KEY (Passeggero) REFERENCES UTENTI (USERNAME); 

ALTER TABLE PRENOTAZIONI ADD CONSTRAINT FK_PRENOTAZIONI_VIAGGIO 
FOREIGN KEY (Viaggio) REFERENCES VIAGGI(Codv) ON DELETE CASCADE; 

ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI_ARRIVO 
FOREIGN KEY (Luogo_Arrivo) REFERENCES LUOGHI(ID_LUOGO); 

ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI_PARTENZA 
FOREIGN KEY (Luogo_Partenza) REFERENCES LUOGHI(ID_LUOGO); 



ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI_AUTISTA
FOREIGN KEY (Autista) REFERENCES UTENTI(USERNAME); 

ALTER TABLE SOSTE ADD CONSTRAINT FK_SOSTE_ID_VIAGGIO 
FOREIGN KEY (Id_Viaggio) REFERENCES Viaggi(CODV); 

ALTER TABLE SOSTE ADD CONSTRAINT FK_SOSTE_ID_LUOGO 
FOREIGN KEY (Id_Luogo) REFERENCES Luoghi(ID_LUOGO); 

ALTER TABLE GIUDIZI ADD CONSTRAINT FK_GIUDIZI_GIUDICANTE
FOREIGN KEY (Giudicante) REFERENCES UTENTI(Username);

ALTER TABLE GIUDIZI ADD CONSTRAINT FK_GIUDIZI_GIUDICATO 
FOREIGN KEY (Giudicato) REFERENCES UTENTI(Username); 

ALTER TABLE CITTA ADD CONSTRAINT FK_CITTA 
FOREIGN KEY (Provincia) REFERENCES CITTA(CAP); 

ALTER TABLE LUOGHI ADD CONSTRAINT FK_LUOGHI
FOREIGN KEY (CAP_CITTA) REFERENCES CITTA(CAP);

-- CREAZIONE INDICI
CREATE INDEX index_nome_citta ON CITTA(Nome ASC); 

CREATE INDEX index_giudicato ON GIUDIZI(Giudicato ASC); 

-- CREAZIONE SEQUENZE

CREATE SEQUENCE CODV_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCYCLE; 

CREATE SEQUENCE CODICE_PREN_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCYCLE; 

CREATE SEQUENCE CODICE_GIUD_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCYCLE; 

CREATE SEQUENCE ID_LUOGHI_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCYCLE; 

--CREAZIONE UTENTI
CREATE USER cpooling_autista IDENTIFIED BY 5678;

CREATE ROLE autista;

GRANT CONNECT TO Autista;

GRANT SELECT,INSERT ON GIUDIZI TO Autista;

GRANT SELECT,INSERT ON VIAGGI TO Autista;

GRANT SELECT ON PRENOTAZIONI TO Autista;

GRANT SELECT ON CITTA TO Autista;

GRANT SELECT ON LUOGHI TO Autista;

GRANT SELECT ANY SEQUENCE TO Autista;

GRANT Autista TO cpooling_autista;




CREATE USER cpooling_passeggero IDENTIFIED BY 9876;

CREATE ROLE Passeggero;

GRANT CONNECT TO Passeggero;

GRANT INSERT,SELECT ON PRENOTAZIONI TO Passeggero;

GRANT SELECT ON VIAGGI TO Passeggero;

GRANT SELECT ON CITTA TO Passeggero;

GRANT SELECT ON LUOGHI TO Passeggero;

GRANT SELECT,INSERT ON GIUDIZI TO Passeggero;

GRANT Passeggero TO cpooling_passeggero;

-- CREAZIONE TRIGGER

CREATE OR REPLACE TRIGGER CHIUSURA_VIAGGIO
AFTER UPDATE ON PRENOTAZIONI 
FOR EACH ROW 
DECLARE 
CONTEGGIO INTEGER;
NUMERO INTEGER;
BEGIN
SELECT COUNT(*) INTO CONTEGGIO
FROM PRENOTAZIONI 
WHERE VIAGGIO=:OLD.VIAGGIO AND STATO='Accettata ';
SELECT NUM_POSTI_DISPONIBILI INTO NUMERO
FROM VIAGGI
WHERE CODV=:NEW.VIAGGIO;
IF NUMERO=CONTEGGIO THEN
UPDATE VIAGGI SET STATO='Chiuso'
WHERE CODV=:NEW.VIAGGIO;
END IF;
END;

CREATE OR REPLACE TRIGGER CONTROLLO_DATA_VIAGGIO
BEFORE INSERT ON VIAGGI 
FOR EACH ROW
DECLARE 
ERRORE EXCEPTION;
BEGIN
IF :NEW.DATA_P<TO_CHAR(SYSDATE,'DD-Mon-YYYY')THEN RAISE ERRORE;
END IF;
EXCEPTION WHEN ERRORE THEN 
RAISE_APPLICATION_ERROR (-20001,'Data non valida!');
END;

CREATE OR REPLACE TRIGGER Controllo_Data_Documento          
BEFORE INSERT ON PASSEGGERI 
FOR EACH ROW 
DECLARE 
Errore EXCEPTION; 
BEGIN 
IF :NEW.SCAD_DOC<TO_CHAR(SYSDATE,'DD-Mon-YYYY') 
THEN RAISE Errore; 
END IF; 
EXCEPTION 
WHEN Errore THEN RAISE_APPLICATION_ERROR (-20002,'Documento scaduto!'); 
END; 

CREATE OR REPLACE TRIGGER Controllo_Data_Patante          
BEFORE INSERT ON AUTISTI 
FOR EACH ROW 
DECLARE 
Errore EXCEPTION; 
BEGIN 
IF :NEW.SCAD_PAT<TO_CHAR(SYSDATE,'DD-Mon-YYYY') 
THEN RAISE Errore; 
END IF; 
EXCEPTION 
WHEN Errore THEN RAISE_APPLICATION_ERROR (-20003,'Patente scaduta!'); 
END; 

CREATE OR REPLACE TRIGGER AGG_PRENOTAZIONI_ATTESA_PLUS
AFTER INSERT ON PRENOTAZIONI
FOR EACH ROW 
BEGIN
UPDATE VIAGGI
SET NUM_ATTESA=NUM_ATTESA+1
WHERE CODV=:NEW.VIAGGIO;
END;

CREATE OR REPLACE TRIGGER AGG_PRENOTAZIONI_ATTESA_MINUS
AFTER UPDATE ON PRENOTAZIONI 
FOR EACH ROW
BEGIN 
IF(:OLD.STATO='In_Attesa' AND :NEW.STATO='Accettata') OR
(:OLD.STATO='In_Attesa' AND :NEW.STATO='Rifiutata') THEN 
    UPDATE VIAGGI
    SET NUM_ATTESA=NUM_ATTESA-1
    WHERE CODV=:NEW.VIAGGIO;
END IF;
END;

--CREAZIONE PROCEDURA PER INSERIMENTO FOTO UTENTE
--CREO PRIMA UNA DYRECTORI NELLA QUALE SALVARE TUTTE LE FOTO
create or replace directory FILE_DIR as 'C:\Progetto\Foto';
--CREO LA PROCEDURA DA ESEGUIRE

CREATE OR REPLACE PROCEDURE INSERT_USER (IN_USER IN VARCHAR2, 
IN_PW IN VARCHAR2,IN_NOME IN VARCHAR2,IN_COGNOME IN VARCHAR2, 
IN_SESSO IN CHAR,IN_NASCITA IN DATE,IN_EMAIL IN VARCHAR2,
IN_CELL IN NUMBER,IN_VIA IN VARCHAR2,IN_CITTA IN VARCHAR2,
IN_CAP IN NUMBER,IN_FILENAME IN VARCHAR2) AS
MYFILE BFILE:=BFILENAME('FILE_DIR',IN_FILENAME);
MYBLOB BLOB;
LUN_FILE BINARY_INTEGER;
BEGIN
DBMS_LOB.FILEOPEN(MYFILE,DBMS_LOB.FILE_READONLY);
LUN_FILE :=DBMS_LOB.GETLENGTH(MYFILE);
DBMS_LOB.CREATETEMPORARY(MYBLOB,FALSE);
DBMS_LOB.LOADFROMFILE(MYBLOB,MYFILE,LUN_FILE);

INSERT INTO UTENTI (USERNAME,PASSWORD,NOME,COGNOME,SESSO,DATA_NASCITA,
EMAIL,FOTO,CELLULARE,VIA,CITTA,CAP,NOMEFILE)

VALUES (IN_USER,IN_PW,IN_NOME,IN_COGNOME,IN_SESSO,IN_NASCITA,
IN_EMAIL,MYBLOB,IN_CELL,IN_VIA,IN_CITTA,IN_CAP,IN_FILENAME);

DBMS_LOB.FILECLOSE(MYFILE);
END;
--TEST
EXEC INSERT_USER('GDC','12345678','GUIDO','DI CHIARA','M',to_date('22-Apr-1997'),'GUIDO@GMAIL.COM',3401278482,'SAN NICOLA VARCO','VENTICANO',83030,'TEST.jpg');

--PROCEDURA PER ESTRAZIONE FOTO DAL DATABASE

create or replace procedure extract_foto(in_user in varchar2) AS 
myblob BLOB; 
lun_file BINARY_INTEGER; 
myname UTENTI.username%type; 
myfile UTL_FILE.FILE_TYPE;
appo_raw RAW(32760); 
buffer_length number := 32760; 
wrote_length number := 0; 
begin 
  select foto, nomefile, dbms_lob.getlength(foto) 
    into myblob, myname, lun_file 
    from UTENTI
   where username=in_user; 
  myfile := utl_file.fopen('FILE_DIR', myname,'wb', 32760); 
  while lun_file>wrote_length loop 
     dbms_lob.read(myblob,buffer_length,wrote_length+1,appo_raw); 
     utl_file.put_raw(myfile,appo_raw); 
     utl_file.fflush(myfile);  
     wrote_length := wrote_length + buffer_length; 
  end loop; 
  utl_file.fclose(myfile); 
end; 

EXEC extract_foto('GDC');

--procedura archiviazione nelle tabelle storico 
CREATE OR REPLACE PROCEDURE archivia AS 
BEGIN 
DECLARE 
CURSOR c_viaggi IS SELECT codv FROM viaggi WHERE data_p < SYSDATE; 
codice_viaggio viaggi.codv%TYPE; 
BEGIN 
OPEN c_viaggi;  
INSERT INTO storico_viaggi 
SELECT * 
FROM viaggi WHERE data_p < SYSDATE;
LOOP 
FETCH c_viaggi INTO codice_viaggio; --leggo il codice_spettacolo i-esimo spettacolo 
EXIT WHEN c_viaggi%NOTFOUND; 
-- INSERT PHASE 
INSERT INTO storico_prenotazioni 
SELECT * 
FROM prenotazioni WHERE viaggio=codice_viaggio; 
-- DELETE PHASE 
DELETE FROM prenotazioni WHERE viaggio=codice_viaggio;
END LOOP;
CLOSE c_viaggi; 
DELETE FROM viaggi WHERE data_p < SYSDATE; 
COMMIT; 
END; 
END archivia; 

--CREAZIONE SCHEDULE PER ARCHIVIAZIONE MENSILE DI VIAGGI E PRENOTAZIONI 
BEGIN 
DBMS_SCHEDULER.CREATE_SCHEDULE('backup', 
REPEAT_INTERVAL =>'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=5;BYMINUTE=0;BYSECOND=0;'); 
END; 
-- Il 1o di ogni mese alle 06:00 viene eseguita la stored procedure di archiviazione
BEGIN 
DBMS_SCHEDULER.CREATE_JOB ( 
job_name =>'backup_mensile', 
schedule_name =>'backup', 
job_type =>'STORED_PROCEDURE', 
job_action =>'archivia', 
enabled => FALSE 
); 
END; 
--PER ATTIVARE IL BACKUP ESEGUIRE
exec dbms_scheduler.enable('backup_mensile');


--TRIGGER GESTIONE CANCELLAZIONE UTENTE
EXEC INSERT_USER('UTENTE CANCELLATO','QWERTYUIOPASDFGHJKL','SCONOSCIUTO','SCONOSCIUTO','?',to_date('01-Gen-2000'),'SCONOSCIUTO',00000000000,'SCONOSCIUTO','SCONOSCIUTO',00000,'UNKNOWN.jpg');

DELETE FROM UTENTI WHERE USERNAME='GDC';

CREATE OR REPLACE TRIGGER CANCELLAZIONE_UTENTE
AFTER DELETE ON UTENTI 
FOR EACH ROW
BEGIN

UPDATE VIAGGI SET AUTISTA='UTENTE CANCELLATO'
WHERE AUTISTA=:OLD.USERNAME;

UPDATE GIUDIZI SET GIUDICANTE='UTENTE CANCELLATO'
WHERE GIUDICANTE=:OLD.USERNAME;

DELETE FROM GIUDIZI WHERE GIUDICATO=:OLD.USERNAME;

UPDATE PRENOTAZIONI SET PASSEGGERO='UTENTE CANCELLATO'
WHERE PASSEGGERO=:OLD.USERNAME;

UPDATE STORICO_VIAGGI SET AUTISTA='UTENTE CANCELLATO'
WHERE AUTISTA=:OLD.USERNAME;

UPDATE STORICO_PRENOTAZIONI SET PASSEGGERO='UTENTE CANCELLATO'
WHERE PASSEGGERO=:OLD.USERNAME;

delete from passeggeri where usern=:OLD.username;
delete from autisti where usern=:OLD.username;



END;

-- POPOLAMENTO BASE DI DATI


EXEC INSERT_USER('GDC','12345678','GUIDO','DI CHIARA','M',to_date('22-Apr-1997'),'GUIDO@GMAIL.COM',3401278482,'SAN NICOLA VARCO','VENTICANO',83030,'TEST.jpg');
EXEC INSERT_USER('AGB','12345677','ANCO','GUARINO LOBBY','M',to_date('21-Mag-1978'),'ANCOMARZIO@GMAIL.COM',340127892,'SANNICOLA AL SANNIO','ARISTIDE',83930,'TEST1.jpg');
EXEC INSERT_USER ('ALB','12345677','ALFONSO','LE BOTTE','M',to_date('13-Gen-1995'),'LEBOTTE@GMAIL.COM',340127832,'IMMAGINARIA','PIANURALAND',83920,'TEST2.jpg');
EXEC INSERT_USER ('DD','12355617','DARIO','DANILO','M',to_date('13-Ott-1955'),'DANILO@GMAIL.COM',340127832,'DEL MARE','POZZUOLI',83620,'TEST3.jpg');
EXEC INSERT_USER ('AR','12255677','ANNA','RELLA','F',to_date('14-Feb-1992'),'ANNARE@GMAIL.COM',340127232,'DALESSIO','FORCELLOPOLI',83420,'TEST4.jpg');
EXEC INSERT_USER ('UL','12150677','UGO','LADORO','M',to_date('1-Apr-1992'),'UGOLADORO@GMAIL.COM',340127032,'DEI CANTANTI','SARRI',85420,'TEST5.jpg');
EXEC INSERT_USER ('MH17','17171717','MAREK','HAMSIK','M',to_date('27-Lug-1987'),'ILCAPITANO@GMAIL.COM',340117232,'DELLA FEDELTA','VERSOILSOGNO',83410,'TEST6.jpg');
EXEC INSERT_USER ('CM','12255687','CAR','MNIELLO','M',to_date('19-Mag-1992'),'CARMINIELLO@GMAIL.COM',340124932,'DI QUA','ACCADIA',71021,'TEST7.jpg');

INSERT INTO  PASSEGGERI VALUES ( 'GDC', '00001', to_date('27-Lug-2027') );
INSERT INTO  PASSEGGERI VALUES ( 'AGB', '00002', to_date('27-Lug-2026') );
INSERT INTO  PASSEGGERI VALUES ( 'ALB', '00003', to_date('24-Lug-2027') );
INSERT INTO  PASSEGGERI VALUES ( 'DD', '00004', to_date('27-Lug-2023') );


INSERT INTO AUTISTI VALUES ('AR','11111', to_date('19-Mag-2020'), 'AUDI', 'FASTEX', 'NERO' ) ;
INSERT INTO AUTISTI VALUES ('UL','11100', to_date('13-Mag-2020'), 'KIA', 'PICANTO', 'BLU' ) ;
INSERT INTO AUTISTI VALUES ('CM','11134', to_date('19-Mag-2021'), 'FORD', 'FOCUS', 'LILLA' ) ;
INSERT INTO AUTISTI VALUES ('MH17','17171', to_date('19-Mag-2020'), 'FERRARI', 'J50', 'ROSSA' ) ;

INSERT INTO CITTA VALUES (80124, 'NAPOLI', 80124);
INSERT INTO CITTA VALUES (80126, 'PIANURA', 80124);
INSERT INTO CITTA VALUES (80100, 'AZZURROPOLI', 80101);
INSERT INTO CITTA VALUES (80127, 'POZZUOLI', 80124);
INSERT INTO CITTA VALUES (80101, 'CASERTA', 80101);

INSERT INTO VIAGGI VALUES (CODV_SEQ.NEXTVAL, 'APERTO',  to_date('19-Mag-2018'), '10:08', 40, 3,0, 10.8, 'è POSSIBILE PORTARE UN TROLLEY' , 1, 'NO', 5, 6, 'MH17');
INSERT INTO VIAGGI VALUES (CODV_SEQ.NEXTVAL, 'APERTO',  to_date('18-Mag-2018'), '10:18', 60, 2, 0, 15.7, 'PICCOLI E NON TROPPO PESANTI' , 2, 'NO', 6, 8, 'UL');
INSERT INTO VIAGGI VALUES (CODV_SEQ.NEXTVAL, 'APERTO',  to_date('17-Mag-2018'), '7:08', 151, 1, 0, 30.0, 'NO LA MACCHINA è PICCOLA ' , 2, 'NO', 5, 9, 'AR');
INSERT INTO VIAGGI VALUES (CODV_SEQ.NEXTVAL, 'APERTO',  to_date('15-Mag-2018'), '9:18', 60, 2, 0, 9.7, 'SOLO BAGAGLI A MANO' , 3, 'SI', 9, 5, 'CM');



INSERT INTO LUOGHI VALUES ( 890.333111 , 890.333111 , 80126 , ID_LUOGHI_SEQ.NEXTVAL);
INSERT INTO LUOGHI VALUES ( 890.333112 , 890.333112 , 80100, ID_LUOGHI_SEQ.NEXTVAL);
INSERT INTO LUOGHI VALUES ( 890.333113 , 890.333113 , 80126 , ID_LUOGHI_SEQ.NEXTVAL);
INSERT INTO LUOGHI VALUES ( 890.333114 , 890.333114 , 80127 , ID_LUOGHI_SEQ.NEXTVAL);


INSERT INTO PRENOTAZIONI VALUES (CODICE_PREN_SEQ.NEXTVAL, 'APERTO', 'GDC',  4);
INSERT INTO PRENOTAZIONI VALUES (CODICE_PREN_SEQ.NEXTVAL, 'APERTO', 'GDC',  5);
INSERT INTO PRENOTAZIONI VALUES (CODICE_PREN_SEQ.NEXTVAL, 'APERTO', 'DD',  6 );
INSERT INTO PRENOTAZIONI VALUES (CODICE_PREN_SEQ.NEXTVAL, 'APERTO', 'ALB', 6 );
INSERT INTO PRENOTAZIONI VALUES (CODICE_PREN_SEQ.NEXTVAL, 'APERTO', 'AGB', 6 );


INSERT INTO GIUDIZI VALUES (CODICE_GIUD_SEQ.NEXTVAL, 5, 'IL VIAGGIO è STATO MOLTO SODDISFACENTE, GUIDA TRANQUILLA E PIACEVOLE,MERITA IL PRIMO POSTO' , 'GDC' , 'MH17');
INSERT INTO GIUDIZI VALUES (CODICE_GIUD_SEQ.NEXTVAL, 3, 'IL VIAGGIO NON è STATO DEI MIGLIORI, MACCHINA SCOMODA E PICCOLA' , 'AGB' , 'AR');
INSERT INTO GIUDIZI VALUES (CODICE_GIUD_SEQ.NEXTVAL, 1, 'GUIDA PESSIMA, AUTISTA VOLGARE E PUZZOLENTE, ESPERIENZA SCONSIGLIATA' , 'DD' , 'CM');
INSERT INTO GIUDIZI VALUES (CODICE_GIUD_SEQ.NEXTVAL, 4, 'IL VIAGGIO è STATO CONFERTEVOLE' , 'ALB' , 'UL');

INSERT INTO SOSTE VALUES (8,5);
INSERT INTO SOSTE VALUES (6,6);


delete from utenti where username='CM';
